### ISSUE TITLE
Help needed: Target dont work on atm's 

### ISSUE THREAD

**Issue by xRoyaltyNLx** [JOSH1059/bjj_atmheist#2]
I have no error's and have a rope in my inventory but can't start the heist with the third eye.

i only get the option from banking to use ATM.

**Comment by JOSH1059** [comment]
Its 2 things.

1. You are not in one of the whitelisted vehicles. Go into the config and add the vehicle model you wanna use. Or use one of the 2 I have there by default
2. Your rope item is not named "rope". It is looking for a specific item named rope. I may add the code for the items.lua in qbcore if people want the code to create the item.

**Comment by xRoyaltyNLx** [comment]
I got it i have skinned banks so the hash from the atm is different, Thanks for replying!
